### ISSUE TITLE
export default

### ISSUE THREAD

**Issue by anonimusprogramus** [bryanmylee/svelte-popperjs#1]
Following the example

```javascript
import { createPopperActions } from 'svelte-popperjs';
```
would throw error:

`Uncaught SyntaxError: The requested module '/web_modules/svelte-popperjs.js' does not provide an export named 'createPopperActions'`

Looks like the export needs a little fix, or modify the example.

Thanks.

**Comment by bryanmylee** [comment]
That’s odd. I’m definitely exporting the function.

I’m not too familiar with Node modules, but my compiled Typescript code exports the function like so:

```js
exports.createPopperActions = createPopperActions;
exports.default = { createPopperActions: createPopperActions };
```

This should set the default export to be an object that has the function as a property, as well as non-default exports that you can destructure with `{}`.

I’ll look into it, thanks for the issue!

**Comment by bryanmylee** [comment]
@anonimusprogramus Out of curiosity, what does your `svelte-popperjs.js` file contain?

**Comment by anonimusprogramus** [comment]
Here's my svelte-popperjs.js

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = require("@popperjs/core");
function createPopperActions() {
    var popperInstance;
    var referenceNode;
    var contentNode;
    var options;
    function referenceAction(node) {
        referenceNode = node;
        return {
            destroy: function () {
                if (popperInstance) {
                    popperInstance.destroy();
                    popperInstance = null;
                }
            }
        };
    }
    function contentAction(node, popperOptions) {
        contentNode = node;
        options = popperOptions;
        popperInstance = core_1.createPopper(referenceNode, contentNode, options);
        return {
            update: function (popperOptions) {
                options = popperOptions;
                if (popperInstance)
                    popperInstance.setOptions(options);
            },
            destroy: function () {
                if (popperInstance) {
                    popperInstance.destroy();
                    popperInstance = null;
                }
            }
        };
    }
    return [referenceAction, contentAction];
}
exports.createPopperActions = createPopperActions;
exports.default = { createPopperActions: createPopperActions };
```

**Comment by anonimusprogramus** [comment]
I finnaly got it running by manually copying your [index.ts](https://github.com/bryanmylee/svelte-popperjs/blob/master/src/index.ts) and customizing as js file.

One thing I forgot to mention is that I'm using svelte + snowpack, sorry. I find some libs atm aren't compatible with snowpack.

Thank you

**Comment by bryanmylee** [comment]
Ah I see.

Is there anything I can do to better support Snowpack?

**Comment by anonimusprogramus** [comment]
I don't know, still learning js :).

I'm closing the issue, thank you for your respond.
