### ISSUE TITLE
How to use actions on two elements

### ISSUE THREAD

**Issue by PlkMarudny** [bryanmylee/svelte-popperjs#13]
How to use actions on two elements? For example in this [REPL](https://svelte.dev/repl/c2fbf0910f354bb9b69bfa8cb591859b?version=3.37.0) a tooltip is positioned by the latter binding only.

**Comment by bryanmylee** [comment]
You will have to create two sets of actions, as each pair has one lifecycle and represent one instance of the Popper engine.

In your case, you will have to do the following:

```svelte
<script>
  const [ref1, content1] = createPopperActions(...);
  const [ref2, content2] = createPopperActions(...);
</script>
```

**Comment by PlkMarudny** [comment]
This works, thanks.
