### ISSUE TITLE
Lint error with virtual elements

### ISSUE THREAD

**Issue by CrendKing** [bryanmylee/svelte-popperjs#19]
Popper supports [Virtual Elements](https://popper.js.org/docs/v2/virtual-elements/) so that user can make the popover work without attaching statically to one actual element. However, `ReferenceAction` of this component currently [hardcodes](https://github.com/bryanmylee/svelte-popperjs/blob/38a0541d53217d946e91ac2ccb7e8c368e78ea72/src/index.ts#L12) the parameter type to be `Element`. This causes the following lint error
```
Argument of type '{ getBoundingClientRect: () => DOMRect; contextElement: HTMLElement; }' is not assignable to parameter of type 'Element'
```
Maybe change it to something like `Element | VirtualElement`?

**Comment by bryanmylee** [comment]
I'll take a look into it and work on a solution this weekend!

**Comment by bryanmylee** [comment]
Check out release `v1.2.11`!

**Comment by CrendKing** [comment]
Thanks. Works.
