### ISSUE TITLE
Add docs for virtual element example

### ISSUE THREAD

**Issue by einarpersson** [bryanmylee/svelte-popperjs#20]
I'd like to use this for a tooltip that follows the cursor.

I am looking at [popperjs virtual elements](https://popper.js.org/docs/v2/virtual-elements/) in the official docs, but it is not clear for me how to use this action approach.

It seems as if [this recent commit](https://github.com/bryanmylee/svelte-popperjs/commit/2a94463a3691d96c8b95010d1f54a9a56dba84ac) would allow for it, but no instructions are provided.

Could you help out by adding a brief example?

**Comment by bryanmylee** [comment]
Hey @einarpersson, I've just looked into the example for virtual elements and using it with this library is not very smooth at the moment.

I can provide a quick example on how to use it, but I'll also release an update to allow passing a writable virtual element to the ref action.

For now, you can use this:

```svelte
<script lang="ts">
  import {createPopperActions} from 'svelte-popperjs';

  const [ref, content, getInstance] = createPopperActions();

  const mousemove = (ev: MouseEvent) => {
    x = ev.clientX;
    y = ev.clientY;
  };
  let x = 0;
  let y = 0;
  $: getBoundingClientRect = () => ({
    width: 0,
    height: 0,
    top: y,
    right: x,
    bottom: y,
    left: x,
  } as DOMRect);
  let virtualElement = { getBoundingClientRect };
  // reassign getBoundingClientRect whenever it updates and update the instance.
  $: (virtualElement.getBoundingClientRect = getBoundingClientRect), getInstance()?.update();

  ref(virtualElement);
</script>

<div use:content>I follow the mouse</div>
```

I've created a sample repository here to test it out too: https://github.com/bryanmylee/example-svelte-popperjs-virtual-element

**Comment by bryanmylee** [comment]
Closed by #22.

**Comment by bryanmylee** [comment]
@einarpersson You can refer to the API section on the README for an example of how to use the new API.

**Comment by einarpersson** [comment]
@bryanmylee Wow, very cool. Thanks for super quick feedback and implementation. Will try it out!
