### ISSUE TITLE
Version 1.3 is not exporting types

### ISSUE THREAD

**Issue by potty** [bryanmylee/svelte-popperjs#23]
Hi, I found out there are no types in v1.3 unfortunately. Difference between v1.2 and v1.3 https://tppr.me/DirPK

**Comment by bryanmylee** [comment]
Thanks for the report and sorry for the mistake. Seems like the types are being exported to the wrong directory. I'll update the configuration.

**Comment by bryanmylee** [comment]
Should be fixed in v1.3.2.
