### ISSUE TITLE
Expose popper instance

### ISSUE THREAD

**Issue by bluwy** [bryanmylee/svelte-popperjs#3]
Hello,

It would be nice if the popper instance is exposed as a third element of the returned array. And probably make it a readable store too, since the actions will very likely to only ever be used in a component.

Reason being that I'm currently implementing transitions on the content element like this:

```svelte
<div use:ref />
<div use:content>
  {#if show}
    <div>Surprise</div>
  {/if}
</div>
```

This way the styling on the content will always persist and the transition don't suddenly teleport to another place. But since the actions has no way of telling when `show` change, popper doesn't recalculate the styles. So I needed to access the instance's `update` method to manually trigger the recalculation.

I've forked the code into my project which exposes the readable instance store and it worked splendidly so I hoped this can be implemented here too.

I can send a PR if given the green light.

**Comment by bluwy** [comment]
Some time had passed and I hacked a solution without exposing the popper instance. I took advantage of the `referenceAction`'s returned `update` function (which wasn't being used) and made it automatically update popper whenever the `referenceAction`s options change. So now instead of:

```svelte
<script>
  let show = false
  const [ref, content, popper] = createPopperActions()
  $: show && $popper?.update()
</script>

<div use:ref />
<div use:content>
  {#if show}
    <div>Surprise</div>
  {/if}
</div>
```

It's now:

```svelte
<script>
  let show = false
  const [ref, content] = createPopperActions()
</script>

<div use:ref={show} />
<div use:content>
  {#if show}
    <div>Surprise</div>
  {/if}
</div>
```

Curious on your take on both solutions.

**Comment by bluwy** [comment]
New day today and I realized that persisting the content element like the code above isn't a really good solution since the instance is constantly updating on scroll and resize events even when not showing.

I reverted in nesting the content in the if statement and found that transitions do work properly after all, provided that the transition directive is nested in the content element. So now my code looks like:

```svelte
<script>
  let show = false
  const [ref, content] = createPopperActions()
</script>

<div use:ref />
{#if show}
  <div use:content>
    <div transition:fly>Surprise</div>
  </div>
{/if}
```

So now I don't need to access the popper instance anymore. Sorry for the issue! :sweat_smile: I'll close this now to keep the repo clean.

**Comment by bryanmylee** [comment]
@bluwy Surprisingly, I recently added the option to access the Popper instance via an anonymous function returned as the 3rd element of the array.

I see that you no longer needed the option to do so, but it’s useful if you need to manually call `instance.update()`.
