### ISSUE TITLE
Uncaught (in promise) ReferenceError: process is not defined in createPopper.js:80 

### ISSUE THREAD

**Issue by SarcevicAntonio** [bryanmylee/svelte-popperjs#7]
I've been looking for a good popperjs svelte wrapper for my datepicker component and this seems like a good one from an usage standpoint.

But the issue I get is that when opening the datepicker (using the calendar emoji button) the lib throws an error and JS "crashes".

Full Log:
```
createPopper.js:80 Uncaught (in promise) ReferenceError: process is not defined
    at Object.setOptions (createPopper.js:80)
    at createPopper (createPopper.js:214)
    at initPopper (index.es.js:10)
    at contentAction (index.es.js:31)
    at Object.mount [as m] (Datepicker.svelte:62)
    at Object.update [as p] (Datepicker.svelte:61)
    at update (index.mjs:764)
    at flush (index.mjs:732)
``` 

[I've pushed a branch to my repo trying to use this lib](https://github.com/SarcevicAntonio/as-datepicker/tree/svelte-popperjs-issue)

simply clone / degit, `npm install` and `npm run dev` then click on the calendar emoji to open the picker. 

[`src/Datepicker.svelte`](https://github.com/SarcevicAntonio/as-datepicker/blob/svelte-popperjs-issue/src/Datepicker.svelte) uses the lib

if the usage is wrong please let me know!

**Comment by bryanmylee** [comment]
This is an issue with your Rollup configuration.

PopperJS depends on the `process` global variable, but something with Rollup is causing it to be undefined.

You can resolve this by using `rollup-plugin-replace`:

```bash
npm i -D @rollup/plugin-replace
```

Add the plugin to your Rollup config:
```
plugins: [
  replace({ 'process.env.NODE_ENV': JSON.stringify( 'production' ) }),
  // ...other plugins
]
```

Let me know if there are any issues!

**Comment by bestguy** [comment]
I realize this is a popper issue, but requiring this rollup fix makes it impossible to use your library in svelte repl:  
https://svelte.dev/repl/f4d002afcdce44ce8402100abd615436?version=3.38.2

(console error shows same issue)

An alternative would be if you import from the popper esm build instead:
```javascript
import { createPopper, Instance, OptionsGeneric, Modifier } from '@popperjs/core/dist/esm/popper';
```

**Comment by bryanmylee** [comment]
@bestguy I've always had trouble getting it to work with the REPL, and I appreciate the help with exploring solutions!

However, the build files from `@popperjs/core/dist/esm` does not contain any type definitions and breaks most of the TypeScript typings on the library. I can't seem to import directly from the ESM build either, as it does not seem to be exposed by the package.

**Comment by bestguy** [comment]
I see, hmm yes this is a pain.  I'll try seeing if another solution. Thanks for the quick look.

**Comment by blindfish3** [comment]
Suggestion: document the fact there's an issue running this in the Svelte REPL :pray:
